#!/bin/zsh

icons=(
	"16 1 icon_16x16.png"
	"16 2 icon_16x16@2x.png"
	"32 1 icon_32x32.png"
	"32 2 icon_32x32@2x.png"
	"128 1 icon_128x128.png"
	"128 2 icon_128x128@2x.png"
	"256 1 icon_256x256.png"
	"256 2 icon_256x256@2x.png"
	"512 1 icon_512x512.png"
	"512 2 icon_512x512@2x.png"
)

ICON="/Users/pritam/sample.icon"
ICONSET="$TMPDIR/MyIcon.iconset"
OUT="$ICONSET"

mkdir -p "$OUT"

export_icon() {
	local w=$1
	local h=$2
	local scale=$3
	local name=$4

	"/Applications/Icon Composer.app/Contents/Executables/ictool" "$ICON" \
		--export-image \
		--output-file "$OUT/$name" \
		--platform macOS \
		--rendition Default \
		--width "$w" \
		--height "$h" \
		--scale "$scale"
}

for entry in "${icons[@]}"; do
	read w scale name <<<"$entry"
	export_icon "$w" "$w" "$scale" "$name"
done

# THE WORKING CONVERSION COMMAND
iconutil -c icns "$ICONSET" -o MyIcon.icns

echo "🎉 Created MyIcon.icns successfully"
